version: '3.8'
services:
  mysql:
    image: 'mysql:5.7'
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    container_name: 'mysql1'
  drupal:
    image: 'drupal:8'
    ports:
      - 8080:80
    volumes:
      - ./modules:/var/www/html/modules
    depends_on:
      - mysql
    restart: always
volumes:
  data:
    
